# ==========================================
# Application Configuration
# ==========================================
spring.application.name=TailorsShopMS


# ==========================================
# MySQL Database Configuration - Railway
# ==========================================
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ==========================================
# JPA / Hibernate Configuration
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true


# ==========================================
# Logging
# ==========================================
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


# ==========================================
# Jackson
# ==========================================
spring.jackson.serialization.fail-on-empty-beans=false